jwt:
  secret: 2383n45394mcubdfisdASDHJLGSdfiksn98378nsmhjd
  lifetime: 30m
  refresh_lifetime: 30d

server:
  servlet:
    context-path: "/api/v1" # change this on big updates on server side

spring:
  application:
    name: molniya_backend

  datasource:
    url: jdbc:postgresql://localhost:5455/molniya_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  docker:
    compose:
      enabled: false

# локально не нужны метрики, трейсинг и пр.
management:
  endpoints:
    web:
      exposure:
        include: health   # только health-check
  endpoint:
    health:
      show-details: never # не палим детали локально